# docker-compose.yml (root)

services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: i2r
      POSTGRES_PASSWORD: i2rpass
      POSTGRES_DB: i2r
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"

volumes:
  pgdata:
